# Generated by Django 4.1.6 on 2023-02-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="caption",
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
