# Generated by Django 4.1.6 on 2023-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote_site", "0002_remove_tag_caption_tag_name_alter_author_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="quote_site.tag"),
        ),
    ]
