# Generated by Django 4.1.6 on 2023-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote_site", "0003_alter_quote_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="borndate",
            new_name="born_date",
        ),
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(related_name="quotes", to="quote_site.tag"),
        ),
    ]
